// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CountryCity.Models
{
    public partial class City
    {
        public int Id { get; set; }
        public string CityName { get; set; }
        public int? ZipCode { get; set; }
        public int CountryId { get; set; }

        public virtual Country Country { get; set; }
    }
}